# permissions for end users to view gatewayconfigurations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: gatewayconfiguration-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gateway-api-tyk
    app.kubernetes.io/part-of: gateway-api-tyk
    app.kubernetes.io/managed-by: kustomize
  name: gatewayconfiguration-viewer-role
rules:
- apiGroups:
  - gateway.buraksekili.github.io
  resources:
  - gatewayconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - gateway.buraksekili.github.io
  resources:
  - gatewayconfigurations/status
  verbs:
  - get
