# permissions for end users to edit tykgateways.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: tykgateway-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: gateway-api-tyk
    app.kubernetes.io/part-of: gateway-api-tyk
    app.kubernetes.io/managed-by: kustomize
  name: tykgateway-editor-role
rules:
- apiGroups:
  - gateway.buraksekili.github.io
  resources:
  - tykgateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gateway.buraksekili.github.io
  resources:
  - tykgateways/status
  verbs:
  - get
