apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: store-routes
spec:
  parentRefs:
    - name: tyk-gateway # It means Gateway resource named tyk/tyk-gateway from gateway.networking.k8s.io
  hostnames:
    - "foo.com"
  rules:
    - matches:
      - path:
          value: /bar
      - path:
          value: /get
      backendRefs:
      - name: my-service1
        port: 8080
      - name: my-service2
        port: 8080
